import express from 'express';
import session from 'express-session';
import flash from 'express-flash';
import lineLoginMiddleware from './lineLogin';
import lineBot from './linebot';
import config from '../config/config';
import adminViewRouter from './adminView';
import adminApiRouter from './adminApi';
const app = express();
app.set('view engine', 'ejs');
app.set('views', './views');
app.use(session({ secret: 'F@##$FASDFWERG$#%$%&%', cookie: { maxAge: 60000 }}));
app.use(flash());
app.post('/line', lineBot.parser());
app.get('/le', lineLoginMiddleware);
app.use('/admin', adminViewRouter);
app.use('/api/admin', adminApiRouter);
app.all('*', (req, res) => res.redirect(config.officialUrl));
app.listen(process.env.PORT || 3000);
console.log(`server start success ${process.env.PORT ? '' : 'port: 3000'}`);
